dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install scispacy
  - pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.0/en_core_sci_sm-0.2.0.tar.gz
script:
  - cd negspacy
  - python -m pytest test.py